### ISSUE TITLE
When stylishask is enabled, cursor jumps to the beginning of .hs file on save

### ISSUE THREAD

**Issue by altern** [alx741/vim-stylishask#3]
I understand that stylishask reloads the file on save, but is it possible for it to leave cursor at its current position?

**Comment by alx741** [comment]
It should... please let me know your `vim --version` output to try and reproduce the issue

**Comment by altern** [comment]
NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by timmyjose** [comment]
I was facing the same issue (cursor moving to line 1, col 1 upon saving the buffer), and created a small PR, which I have tested on my local setup -  https://github.com/alx741/vim-stylishask/pull/4

**Comment by alx741** [comment]
Fix #4 by @timmyjose
